### ISSUE TITLE
Cannot combine using the null-coalescing operator with the exponentiation operator

### ISSUE THREAD

**Issue by sebastiendan** [sebastiendan/react-ts-nullcoalescing-exponentiation#1]
[Origin issue](https://github.com/ethereumjs/ethereumjs-monorepo/issues/2595)

With the current version `main` version ([commit](https://github.com/sebastiendan/react-ts-nullcoalescing-exponentiation/commit/cc2bbdd6b46a77d30964b811dd054603f6ebf7c1)), the instantiation of a trie from `@ethereumjs/trie` generates the following error on page load:

<details>
<summary>Error logs: exponentiation operator (**) with BigInt (@chainsafe/ssz)</summary>
```
Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at ./node_modules/@chainsafe/ssz/lib/type/uint.js (uint.ts:10:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@chainsafe/ssz/lib/index.js (index.ts:12:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/util/dist/ssz.js (ssz.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/util/dist/index.js (index.ts:39:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object.<anonymous> (branch.ts:2:1)
    at ./node_modules/@ethereumjs/trie/dist/trie/node/branch.js (branch.ts:6:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/trie/node/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/trie/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object.<anonymous> (range.ts:1:1)
    at ./node_modules/@ethereumjs/trie/dist/proof/range.js (range.ts:410:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/proof/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/index.js (index.ts:2:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (Step1.tsx:388:1)
    at ./src/components/steps/Step2.tsx (Step2.tsx:268:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (MetaMask.tsx:58:1)
    at ./src/components/MultiStepForm.tsx (MultiStepForm.tsx:132:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (main.chunk.js:19:83)
    at ./src/App.tsx (App.tsx:53:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (useRegisteredTokens.ts:10:1)
    at ./src/index.tsx (index.tsx:21:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at 1 (index.ts:41:1)
```
</details>

A potential solution described here below consists in updating the `browserlist` in `package.json`.
https://github.com/paulmillr/noble-ed25519/issues/23#issuecomment-1028964075

Problem: When changing this list to the value provided in the link above, a former error related to the use of the null coalescing operator is raised.

<details>
<summary>Error logs: Null coalescing operator (??)</summary>
```
index.ts:2 Uncaught Error: Module parse failed: Unexpected token (9:31)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| class MapDB {
|   constructor(database) {
>     this._database = database ?? new Map();
|   }
|   async get(key) {
    at ./node_modules/@ethereumjs/trie/dist/db/map.js (index.ts:2:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/db/index.js (index.ts:2:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (main.chunk.js:12:170)
    at ./src/App.tsx (App.tsx:16:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (App.tsx:16:1)
    at ./src/index.tsx (index.tsx:21:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at 1 (reportWebVitals.ts:16:1)
    at __webpack_require__ (bootstrap:856:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:129
```
</details>

A proposed (and working until `@ethereumjs/trie` is added to the stack) solution was given here below:
https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642

**Comment by acolytec3** [comment]
If you update the `browserslist` field in package.json to something like this:
```json
  "browserslist": [
    "chrome > 52",
    "opera > 39",
    "edge > 14",
    "firefox > 52",
    "safari > 10.1",
    "not dead",
    "not op_mini all"
  ],
```

The issue goes away.  [This issue thread on the babel github repo](https://github.com/babel/babel/issues/13109) provides more detrail.  You can probably use a more general browserlist setting like "last 2 versions"  as well (depending on how old a browser you need to support).  Yoiu can reference the [caniuse section on exponentation for further details](https://caniuse.com/?search=exponentiation).

**Comment by sebastiendan** [comment]
It was my understanding that ts->js transpiling with the right `target` in tsconfig.json in accordance with the caniuse for ECMAScript versions was enough (thought the ts transpiler would have replaced the unsupported features with polyfills), I didn't know we had to modify the `browserlist` as per every single feature used by third party libs.

Thanks anyway for finding the solution! 👍

**Comment by 0xboga** [comment]
I still struggled with this error using Nuxt2 and babel and finally worked with this config: 
`babel: {
        presets: [
            '@babel/preset-env',
            '@babel/preset-typescript'
        ],
        plugins: [
            '@babel/plugin-proposal-optional-chaining',
            '@babel/plugin-proposal-nullish-coalescing-operator'
        ]
    }
`

**Comment by acolytec3** [comment]
That sounds about right. Unfortunately, the defaults for many of these frameworks still support lots of older browsers that don't support modern JavaScript so hard to get around these hacks when you use dependencies that don't transpile to older versions of ECMAScript
